using Ambev.DeveloperEvaluation.Common.Validation;
using Ambev.DeveloperEvaluation.Domain.Common;
using Ambev.DeveloperEvaluation.Domain.Validation;

namespace Ambev.DeveloperEvaluation.Domain.Entities;

/// <summary>
/// Represents a sale transaction record.
/// Follows DDD principles: encapsulates business rules and exposes behaviour methods.
/// Uses the External Identities pattern for Customer and Branch references.
/// </summary>
public class Sale : BaseEntity
{
    /// <summary>Human-readable sequential sale number (auto-generated by the database).</summary>
    public int SaleNumber { get; set; }

    /// <summary>Date and time the sale was made.</summary>
    public DateTime SaleDate { get; set; }

    /// <summary>External identity: customer identifier from the customer domain.</summary>
    public Guid CustomerId { get; set; }

    /// <summary>Denormalized customer name at the time of sale.</summary>
    public string CustomerName { get; set; } = string.Empty;

    /// <summary>External identity: branch identifier from the branch domain.</summary>
    public Guid BranchId { get; set; }

    /// <summary>Denormalized branch name at the time of sale.</summary>
    public string BranchName { get; set; } = string.Empty;

    /// <summary>Total sale amount (sum of all non-cancelled item totals).</summary>
    public decimal TotalAmount { get; set; }

    /// <summary>Whether the entire sale has been cancelled.</summary>
    public bool IsCancelled { get; set; }

    /// <summary>Timestamp when the sale record was created.</summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>Timestamp of the last update, null if never updated.</summary>
    public DateTime? UpdatedAt { get; set; }

    private readonly List<SaleItem> _items = new();

    /// <summary>Read-only collection of line items belonging to this sale.</summary>
    public IReadOnlyCollection<SaleItem> Items => _items.AsReadOnly();

    public Sale()
    {
        CreatedAt = DateTime.UtcNow;
    }

    /// <summary>
    /// Adds an item to the sale and calculates its discount immediately.
    /// </summary>
    /// <param name="item">The sale item to add.</param>
    public void AddItem(SaleItem item)
    {
        item.SaleId = Id;
        item.CalculateDiscount();
        _items.Add(item);
    }

    /// <summary>
    /// Recalculates TotalAmount as the sum of non-cancelled item totals.
    /// </summary>
    public void CalculateTotalAmount()
    {
        TotalAmount = _items
            .Where(i => !i.IsCancelled)
            .Sum(i => i.TotalAmount);
    }

    /// <summary>
    /// Cancels the entire sale. Sets IsCancelled = true and stamps UpdatedAt.
    /// </summary>
    public void Cancel()
    {
        IsCancelled = true;
        UpdatedAt = DateTime.UtcNow;
    }

    /// <summary>
    /// Cancels a single item within the sale and recalculates the sale total.
    /// </summary>
    /// <param name="itemId">The identifier of the item to cancel.</param>
    /// <exception cref="DomainException">Thrown when the item is not found.</exception>
    public void CancelItem(Guid itemId)
    {
        var item = _items.FirstOrDefault(i => i.Id == itemId)
            ?? throw new DomainException($"Item '{itemId}' not found in this sale.");

        item.IsCancelled = true;
        UpdatedAt = DateTime.UtcNow;
        CalculateTotalAmount();
    }

    /// <summary>
    /// Replaces the entire items collection with a new set (used during updates).
    /// Each item is expected to already have its discount calculated.
    /// </summary>
    public void ReplaceItems(IEnumerable<SaleItem> items)
    {
        _items.Clear();
        foreach (var item in items)
        {
            item.SaleId = Id;
            _items.Add(item);
        }
        UpdatedAt = DateTime.UtcNow;
    }

    /// <summary>
    /// Validates the sale using <see cref="SaleValidator"/> rules.
    /// </summary>
    public ValidationResultDetail Validate()
    {
        var validator = new SaleValidator();
        var result = validator.Validate(this);
        return new ValidationResultDetail
        {
            IsValid = result.IsValid,
            Errors = result.Errors.Select(o => (ValidationErrorDetail)o)
        };
    }
}
